version: '3'

services:
    php:
        build:
          context: .
          dockerfile: Dockerfile
        working_dir: /app
        volumes:
            - ./:/app
            # host-volume for composer cache
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            - ./ssl:/var/imported/ssl
            - ./sites-available:/etc/apache2/sites-available
        ports:
            - '80:80'
            - '443:443'
